apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-app.fullname" . }}-server
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: backend
  namespace: employee-system
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-app.labels" . | nindent 8 }}
        app: backend
    spec:
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: "db-credentials"
          ports:
            - containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          