apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-app.fullname" . }}-client
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: frontend
  namespace: employee-system
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      {{- include "employee-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "employee-app.labels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi