apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: employee-system-secret
  namespace: employee-system  
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: "db-credentials"
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: {{ .Values.global.secretName }}
        
   