apiVersion: v1
kind: Service
metadata:
  name: {{ include "employee-app.fullname" . }}-backend
  namespace: employee-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/metrics"
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.server.service.port }}
      protocol: TCP
  selector:
    {{- include "employee-app.labels" . | nindent 4 }}
    app: backend
